//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFVSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int Flight_ID { get; set; }
        public Nullable<int> Ticket { get; set; }
        public Nullable<int> Station { get; set; }
        public Nullable<int> Airplane { get; set; }
        public Nullable<int> Number_of_seats { get; set; }
    
        public virtual Airplanes Airplanes { get; set; }
        public virtual Stations Stations { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
