//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFVSR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSREntities : DbContext
    {
        public VSREntities()
            : base("name=VSREntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplanes> Airplanes { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    }
}
